kramdown:
  auto_ids:   true
  input:      GFM
exclude:
  - node_modules
  - bower_components
  - scss
  - Gemfile*
  - Gruntfile.js
  - HOWTO*
  - package.json
  - README.md
  - TODO.md
baseurl: /
domain_name: 'http://trailblazer.to'
url: 'http://trailblazer.to'
name: "Trailblazer"
imageurl: "http://trailblazer.to/images/go-trailblazer.jpg"
twitter: "@apotonick"
include:
  - .nojekyll
gems:
  - jekyll-redirect-from
  - jekyll-last-modified-at
algolia:
  application_id: 'fill_in'
  index_name: 'trailblazer'
  read_only_api_key: 'fill_in'
  excluded_files:
    - 404.html
    - index.html

